### ISSUE TITLE
Fix note icon, UL marker size, dot-leader

### ISSUE THREAD

**Issue by wmat** [riscv-non-isa/riscv-iommu#345]
Revert the note admonition icon to the older info circle.
Make unordered lists bullets larger.
Add the TOC dot-leader back in.

**Comment by ved-rivos** [comment]
Change codespan font to Jetbrains mono.

**Comment by ved-rivos** [comment]
Make page number column in TOC fixed width so the column does not look wavy.
Make Figure number and Table number column in list of figures and list of tables fixed width so that captions line up and dont look wavy. Perhaps something like below:
```
# List of figures settings
lof:
  label_width: '3em'  # Adjust the width for figure labels
  align: left
  caption:
    indent: '4em'  # Ensure captions align consistently

# List of tables settings
lot:
  label_width: '3em'  # Adjust the width for table labels
  align: left
  caption:
    indent: '4em'  # Ensure captions align consistently
```

**Comment by ved-rivos** [comment]
Bullets could possible be fixed this way:
```
# List settings
list:
  indent: '$horizontal_rhythm * 1.5'
  item_spacing: '$vertical_rhythm / 2'
  bullet:
    font_size: 'round($base_font_size * 1.5)'
    content: '•'
```
